   # .github/workflows/run-sales.yml
   name: Run Sales Data Collection
   on:
     workflow_dispatch:
       inputs:
         start_date:
           description: '시작 날짜 (YYYY-MM-DD)'
           required: true
         end_date:
           description: '종료 날짜 (YYYY-MM-DD)'
           required: true

   jobs:
     collect-sales:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-python@v2
           with:
             python-version: '3.x'
         - run: pip install -r requirements.txt
         - run: python main.py --mode once --start-date ${{ github.event.inputs.start_date }} --end-date ${{ github.event.inputs.end_date }}
         env:
           SUPABASE_URL: https://yaygrcpjimbqswkjlsrr.supabase.co
           SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlheWdyY3BqaW1icXN3a2psc3JyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjcxMzgxOCwiZXhwIjoyMDU4Mjg5ODE4fQ.kIYXwtRdBYHJ_6wcjwlLkAn5D1RGMO18-Ws_yK7c1bo
           USERNAME: yummar
           PASSWORD: 12345678
           STORE_CODES: "101,103,104,105"
